### ISSUE TITLE
Discussion about the transition to Python 3

### ISSUE THREAD

**Issue by jqadev** [gerardpuig/ubuntu-cleaner#12]
Hi @gerardpuig, @jwinnie and others,

according to the upcoming retirement of Python 2, visible here https://pythonclock.org, it may be worth moving to Python 3 and removing the dependence of Python 2.

What are your opinions on this? Maybe you need some help.

Thank you for your great work so far  :+1:

**Comment by gerardpuig** [comment]
Related with #18, it's going to be migrated to python 3 before ubuntu 20.04
