### ISSUE TITLE
Unmet dependency issue while installing on ubuntu 19.10

### ISSUE THREAD

**Issue by ratinggorilla** [gerardpuig/ubuntu-cleaner#18]
I was installing ubuntu-cleaner using following command
1. sudo apt install software-properties-common
2.  sudo add-apt-repository ppa:gerardpuig/ppa
3. sudo apt update
4. sudo apt install ubuntu-cleaner
But in 4th command i got an error 
ERROR:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ubuntu-cleaner : Depends: python-aptdaemon but it is not installable
                  Depends: python-aptdaemon.gtk3widgets but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by gerardpuig** [comment]
hi @ratinggorilla 

Ubuntu repos have dropped the support for python 2.7 on those packages. The code is quite old and should be migrated to python3.
As a workaround, please install the missing packages from ubuntu disco (19.04), you can download the .deb from here
https://packages.ubuntu.com/disco/python-aptdaemon
https://packages.ubuntu.com/disco/python-aptdaemon.gtk3widgets

Download both .deb, and then dpkg -i  ... eventually you have to run apt install -f after that, if you retry to install ubuntu-cleaner the dependencies are met so it goes through :)

I will work on an upgrade to python 3 since on the next LTS (20.04) many people are going to have issues with that as it will have more users.

Sorry for the trouble!

**Comment by Nollie8969** [comment]
Hi Gerard, any news about the new release ?

**Comment by gerardpuig** [comment]
Hi @Nollie8969 yes I am working on a python3 migration, you can already test it if you checkout from master.
I still need to submit the final version to launchpad so the ppa gets updated.

**Comment by Nollie8969** [comment]
Congratulations on your new very fresh build. I just installed your 1.0.5.21-1.all.deb on Ubuntu Cinnamon 20.04. But... it does not run. Usually the .deb works on a coming Ubuntu version (the ppa only after release). Am I too eager ? ;-)

**Comment by gerardpuig** [comment]
Hi @Nollie8969 that is a test build only for Eoan, I'm fixing some dependency issues.
In any case what is the error you are getting? Execute it from the terminal so you will see the logs.

**Comment by gerardpuig** [comment]
@ratinggorilla @Nollie8969 version 1.1.1 is now live for Ubuntu 19.10 (Eoan) with correct python3 dependencies, please if you can test it out that would be great. Looking forward to have a user tested version for ubuntu 20.04 LTS

Any errors report it here, use always the terminal to launch ubuntu-cleaner to see the logs, thanks!

**Comment by Nollie8969** [comment]
No luck. Same as last night. I tried 1.1.1-1_all.deb as package from launchpad (this is what I used to do with former version). It installs, but does not run. 

Same with: 
wget https://launchpad.net/~gerardpuig/+archive/ubuntu/ppa/+files/ubuntu-cleaner_1.1.1-1_all.deb
sudo apt install ./ubuntu-cleaner_1.1.1-1_all.deb
rm ubuntu-cleaner_1.1.1-1_all.deb
It does not run. 

PPA does not run on development. I do not have 19.10 anymore. 

Also tried: git clone https://github.com/gerardpuig/ubuntu-cleaner.git
./ubuntu-cleaner gave error. I'm not familiar with this, though.

**Comment by Nollie8969** [comment]
This is after installing the .deb: 

![Schermafdruk van 2020-04-03 20-04-04](https://user-images.githubusercontent.com/62839988/78391425-a2a6f500-75e6-11ea-8f5c-177f354f36d7.png)

**Comment by Nollie8969** [comment]
Cool! Your system is clean!  Grrreat job !!! 

![Schermafdruk van 2020-04-05 15-11-46](https://user-images.githubusercontent.com/62839988/78499284-06006680-7750-11ea-86b5-0f818edd6384.png)

**Comment by gerardpuig** [comment]
hi @Nollie8969 good to hear that :smile: I just added the 1.1.2 version also on ubuntu 20.04 ppa so you should be able to install it from the ppa directly. So this version is available for Eoan (19.10) and Focal (20.04).

I'm closing this issue since the original issue has been resolved now.
