### ISSUE TITLE
Recommendation:  AppImage

### ISSUE THREAD

**Issue by damianrath** [gerardpuig/ubuntu-cleaner#19]
Commendable effort to make life easier for the non-commandline folks.

Do yourself a favor and create an [AppImage](https://appimage.org/) of your software. No more hassle with dependencies and no installation issues (one file you run from wherever you want) etc etc.

Good luck and keep up the good work!

**Comment by christianbearslyclark** [comment]
Agreed. Maybe a Snap as well !

**Comment by gerardpuig** [comment]
For now I will only maintain the .deb packages. However, feel free to pack it as snap, you can always send a PR so I can merge it and use my launchpad account for it.
