### ISSUE TITLE
no support for Ubuntu vivid?

### ISSUE THREAD

**Issue by Bogotrax** [gerardpuig/ubuntu-cleaner#3]
Hello,

added your repo to my sources.list, but no possibility to install ubuntu-cleaner on Ubuntu 15.04.
Will it be supported/ maintained for 15.04 aswell or can you explain what files I need to build & test it?

Best,

Bogotrax

Edit: found the.deb file under http://ubuntu-cleaner.blogspot.de/; Thanks for providing that program!

**Comment by gerardpuig** [comment]
Hello,

I mainly give support to LTS versions but this one should work with xenial package, can you edit file:
/etc/apt/sources.list.d/gerardpuig-ubuntu-ppa-xenial.list

And where it says vivid change it for xenial and then do sudo apt update & sudo apt install ubuntu ubuntu-cleaner, it should work

**Comment by Bogotrax** [comment]
Hello,

Thanks for your quick reply and the workaround!

Cheers
