### ISSUE TITLE
Fails to launch

### ISSUE THREAD

**Issue by RaspberryKitty1** [gerardpuig/ubuntu-cleaner#33]
I am on lubuntu 18.04.4 and its fully up to date but ubuntu cleaner fails to launch when I try to launch it from term there is a error
```/usr/bin/ubuntu-cleaner:11: PyGIWarning: Gdk was imported without specifying a version first. Use gi.require_version('Gdk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GObject, Gdk, Gtk, Gio
/usr/bin/ubuntu-cleaner:11: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GObject, Gdk, Gtk, Gio
Traceback (most recent call last):
  File "/usr/bin/ubuntu-cleaner", line 15, in <module>
    from ubuntucleaner.settings.debug import enable_debugging
  File "/usr/lib/python2.7/dist-packages/ubuntucleaner/settings/debug.py", line 6, in <module>
    from gi.repository import Gtk, Gdk, Notify
ImportError: cannot import name Notify
```
yes I tried `sudo -H pip install notify` and it still not fix the issue

**Comment by historyb1** [comment]
I have the same error also
`/usr/bin/ubuntu-cleaner:11: PyGIWarning: Gdk was imported without specifying a version first. Use gi.require_version('Gdk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GObject, Gdk, Gtk, Gio
/usr/bin/ubuntu-cleaner:11: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GObject, Gdk, Gtk, Gio
Traceback (most recent call last):
  File "/usr/bin/ubuntu-cleaner", line 15, in <module>
    from ubuntucleaner.settings.debug import enable_debugging
  File "/usr/lib/python2.7/dist-packages/ubuntucleaner/settings/debug.py", line 6, in <module>
    from gi.repository import Gtk, Gdk, Notify
ImportError: cannot import name Notify`

I am using Elementary OS 5

**Comment by gerardpuig** [comment]
Hi @RaspberryKitty1 @historyb1 I've migrated the project to python3, the latest version is 1.1.1 which is built for Ubuntu 19.10 (Eoan), however you can always install it directly from https://launchpad.net/~gerardpuig/+archive/ubuntu/ppa/+files/ubuntu-cleaner_1.1.1-1_all.deb it should work fine also on 18.04.

**Comment by RaspberryKitty1** [comment]
Thanks for updating it.
