### ISSUE TITLE
Package Configs cleaning issue

### ISSUE THREAD

**Issue by MrAnon-dev** [gerardpuig/ubuntu-cleaner#41]
Hi, 

When cleaning "Package Configs", the app hangs forever and only delete one by one, you have to close and open the application for each package.

Ubuntu 20.04 LTS 64bit

Thanks!

![ubuntu-cleaner-bug](https://user-images.githubusercontent.com/65110156/83763383-ecf53280-a678-11ea-9116-05f9f41ce038.png)

**Comment by gerardpuig** [comment]
hi @MrAnon-dev could you please indicate which version are you using? this particular issue was fixed in version 1.1.3

**Comment by MrAnon-dev** [comment]
Hi, 
 1.1.3
![ubuntu-cleaner_1-1-3](https://user-images.githubusercontent.com/65110156/83771772-ecfa3000-a682-11ea-8e08-dc514099cae9.png)

Thanks!

**Comment by gerardpuig** [comment]
hi @MrAnon-dev so is it still happening in your case with 1.1.3 ? Everyone else reported the issue was gone.

**Comment by MrAnon-dev** [comment]
Hi, 

Yes, I think so.

It was on 1.1.2, and when I saw this issue, I left the last config package without delete and upgraded to 1.1.3 but it behaved the same.

In the next kernel update I will try again.

it's just a minor problem, right? I mean, the packages are removed correctly

thank you very much for the support

**Comment by gerardpuig** [comment]
Yes, on version 1.1.2 it did the delete but only the first item. On 1.1.3 this is tested by several people including me and it's working fine, so I'll close this issue for now. I'll also give it a try on the next kernel update.
