### ISSUE TITLE
Kernels not being removed

### ISSUE THREAD

**Issue by skelband** [gerardpuig/ubuntu-cleaner#43]
I started to notice a little while ago that old kernels are not being cleaned.
I just upgraded the kernel, rebooted and ran Ubuntu Cleaner to flush stuff out and leave me with the one kernel that I am running.
It goes through the motions of removing packages and the like, but the kernel files are still there.
```
config-4.15.0-109-generic      memtest86+.elf
config-4.15.0-111-generic      memtest86+_multiboot.bin
grub                           System.map-4.15.0-109-generic
initrd.img-4.15.0-109-generic  System.map-4.15.0-111-generic
initrd.img-4.15.0-111-generic  vmlinuz-4.15.0-109-generic
memtest86+.bin                 vmlinuz-4.15.0-111-generic
```
It's been like this for a while. I have to go into Synaptic and remove them manually.

I'm running this on Linux Mint 19.3 (the Ubuntu-based variant) so there may be some incompatibility of course.

Any ideas?

**Comment by gerardpuig** [comment]
hi @skelband I will try to look into this. An easy alternative is just to execute `sudo apt autoremove` this will remove old kernels.
