### ISSUE TITLE
IP: Not Found

### ISSUE THREAD

**Issue by mr466** [gerardpuig/ubuntu-cleaner#45]
Ubuntu 20.04 Remix Deepin 64Bit

@Desktop:~$ sudo add-apt-repository ppa:gerardpuig/ppa
 Official Ubuntu Cleaner stable repository
 More info: https://launchpad.net/~gerardpuig/+archive/ubuntu/ppa
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Hit:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu focal InRelease                         
Hit:3 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease                 
Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease                  
Hit:5 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease
Ign:6 http://ppa.launchpad.net/flexiondotorg/hal-flash/ubuntu focal InRelease
Hit:7 http://ppa.launchpad.net/gerardpuig/ppa/ubuntu focal InRelease
Hit:8 http://ppa.launchpad.net/peterlevi/ppa/ubuntu focal InRelease
Hit:9 http://ppa.launchpad.net/ubuntudde-dev/stable/ubuntu focal InRelease
Err:10 http://ppa.launchpad.net/flexiondotorg/hal-flash/ubuntu focal Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                      
E: The repository 'http://ppa.launchpad.net/flexiondotorg/hal-flash/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Where to from here?

**Comment by gerardpuig** [comment]
I'm closing this issue. This has nothing to do with the software, most likely a hiccup with the launchpad ppa server at that moment.
