### ISSUE TITLE
Runs with "Error" ????

### ISSUE THREAD

**Issue by mr466** [gerardpuig/ubuntu-cleaner#46]
Ubunbtu 20.04 Remix Depin 64bit

@Desktop:~$ ubuntu-cleaner
/usr/lib/python3/dist-packages/ubuntucleaner/settings/debug.py:7: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Gdk, Gtk, Notify
/usr/bin/ubuntu-cleaner:70: DeprecationWarning: Gdk.threads_init is deprecated
  Gdk.threads_init()
/usr/bin/ubuntu-cleaner:71: PyGIDeprecationWarning: Since version 3.11, calling threads_init is no longer needed. See: https://wiki.gnome.org/PyGObject/Threading
  GObject.threads_init()
[utils.icon][ERROR] guess_from_path failed: 'utf-8' codec can't decode byte 0xfd in position 132: invalid start byte (icon.py:108)
[utils.icon][ERROR] guess_from_path failed: 'utf-8' codec can't decode byte 0xfd in position 132: invalid start byte (icon.py:108)

Did it work?  It said "I was cool" but errors???
Also does not show-up in my software list ... run from terminal only?

**Comment by gerardpuig** [comment]
hi @mr466 how is this installed? Looks like you have run the code without being installed with the .deb file (ppa repository)
