### ISSUE TITLE
Cleaner cannot sustain to clean more than 1200 apt

### ISSUE THREAD

**Issue by sanjaygeeky** [gerardpuig/ubuntu-cleaner#49]
Hello 

Appreicate your work in bringing up the tool
The cleaner closes down once it reaches the apt cache for more than 1200 plus apt packages.

Can you please increase the buffer so that a max of say 5000 packages can be cleaned?

Thanks
Sanjay Mahajan

CIAO

**Comment by gerardpuig** [comment]
hi @sanjaygeeky I have released a new version which should fix that memory issue. Could you please test it on this version 1.1.4? Reopen the issue if you still experience issues
