### ISSUE TITLE
Fail to launch in WSL Ubuntu

### ISSUE THREAD

**Issue by yqs112358** [gerardpuig/ubuntu-cleaner#52]
I am trying to install and use ubuntu-cleaner in newest version of WSL Ubuntu which contains builtin support for GUI. But after installation I fail to launch with error message:
```
Traceback (most recent call last):
  File "/usr/bin/ubuntu-cleaner", line 18, in <module>
    from ubuntucleaner.settings.debug import enable_debugging
  File "/usr/lib/python3/dist-packages/ubuntucleaner/settings/debug.py", line 7, in <module>
    from gi.repository import Gdk, Gtk, Notify
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 132, in load_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name Notify, introspection typelib not found
```
<img width="581" alt="image" src="https://user-images.githubusercontent.com/37969157/179016818-9b1651e0-d3ec-4993-9f06-a183154077ba.png">

I install this package correctly by apt so it is strange for this error. I had also tried something like "sudo pip install Notify" but it doesn't work.

**Comment by yqs112358** [comment]
The system information:
<img width="626" alt="image" src="https://user-images.githubusercontent.com/37969157/179018245-4a869df8-0cb8-45d0-b84f-c427c849e7d9.png">

**Comment by TasMania17** [comment]
This also happens with updated Ubuntu 22.04. I think it's because Ubuntu (build on Debian testing) now uses  python3 version 10. To check:

python3 -V
Python 3.10.4
Looks like ubuntu-cleaner was built on python3.6. I hope Gerard is able to fix it because its a nice application to have.

**Comment by tjw123hh** [comment]
same problem on kubuntu 22.04

**Comment by gerardpuig** [comment]
hi all, it works for me perfectly on ubuntu 22.04, the .deb package has a dependency on gir1.2-notify-0.7 but if this is somehow not installed then it will cause this issue. So could you please try to install that `sudo apt install gir1.2-notify-0.7` and see if that makes it work?

**Comment by TasMania17** [comment]
Hi Gerard works with the dep and ubuntu-cleaner from the repository. Thanks for fixing :)
