### ISSUE TITLE
PPA doesn't work any more (Depreciated?)

### ISSUE THREAD

**Issue by barragh** [gerardpuig/ubuntu-cleaner#53]
Hi,
I have tried adding the PPA to Linux Mint to re-install Ubuntu Cleaner but there is an error message every time and I think it says it is 'depreciated'. It won't install Ubuntu Cleaner and doing sudo apt update/upgrade comes up with the above error every time. My OS is a fresh install and I had to remove the PPA because it just wasn't working.
Just thought you should know.
Regards,
Barragh

**Comment by PunchyRock** [comment]
I also had the same problem today. And I fixed it by running
`cd /etc/apt`
`sudo cp trusted.gpg trusted.gpg.d`

**Comment by gerardpuig** [comment]
this is due a security issue found in apt-key, it has nothing to do with the ppa server (which I have no control at all)
a more detailed explanation can be found here https://itsfoss.com/apt-key-deprecated/

but to simplify ubuntu wants you to separate GPG keys
