### ISSUE TITLE
Build fails?

### ISSUE THREAD

**Issue by jwinnie** [gerardpuig/ubuntu-cleaner#9]
When I try running `sudo python setup.py install` in my Ubuntu 17.10 computer, it complains that it "cannot find the dependencies in the PyPi repository." However, I have installed all of the exact dependencies through `apt`.

`setup.py` needs to be tweaked to discover local packages, as the packages are GNU+Linux/Gtk+ specific and will never be available on PyPi.

**Comment by jwinnie** [comment]
After searching around, I found this:
```
try:
    import usb
except ImportError:
    err += "usb (apt-get install python-usb)\n"
```
https://github.com/riverloopsec/killerbee/blob/master/setup.py

It is not specifying the dependencies via `setuptools` and using its own mechanism.

**Comment by gerardpuig** [comment]
It's always best to install it with the deb file since setup.cfg already includes dependencies.
For development you don't need to install it, just clone it and run it directly.

**Comment by jwinnie** [comment]
Then why is `setup.py` there if it does not work?

**Comment by gerardpuig** [comment]
Agree, will remove it. Code works by just checking out, and in fact setup.py is breaking the .deb installation.

**Comment by gerardpuig** [comment]
`setup.py` is used to create the .deb file (see in Makefile the deb method) so it's useful there. But certainly if it runs once the .deb is installed it breaks it. It should be fixed indeed.
